### ISSUE TITLE
touch_alert_button only seems to work on non-native dialogs

### ISSUE THREAD

**Issue by TeresaP** [jmoody/briar#61]
@jmoody I tried using your alerts methods in my code and touch_alert_button is the only method that isn't working for the Apple ID password dialog because it appears to only work when touching things in non-native dialogs. Is there a way to touch when uia_available? is true?

Edit: Looks like this may work:

```
if uia_available?
      uia_tap(:view, {:marked => "#{button_title}"})
else
...
```

https://github.com/jmoody/briar/blob/develop/lib/briar/alerts_and_sheets/alert_view.rb#L121

**Comment by jmoody** [comment]
@TeresaP Hey!

Poor briar.  Not getting much love these days.

These is the latest and greatest code for interacting with UIAlerts.

https://github.com/calabash/ios-smoke-test-app/blob/master/CalSmokeApp/features/step_definitions/alerts_steps.rb

> uia_available?

These days, `uia_available?` should _always be true_.

**Comment by TeresaP** [comment]
Haha okay I was looking through old posts and saw you refer someone to that Briar code :).  I'll take a look at your CalSmokeApp.  Thanks!
